baseurl = "https://panoramadedados.github.io/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "content/arquivo"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "Panorama de Dados"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Mais"
    writtenBy = "Escrito por"
    readMore = "Ler mais"
    readOtherPosts = "Ler outras publicações"
    newerPosts = "Publicações novas"
    olderPosts = "Publicações antigas"
    minuteReadingTime = "minutos"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Panorama de Dados"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "sobre"
        name = "Sobre"
        url = "/sobre"
      [[languages.en.menu.main]]
        identifier = "arquivo"
        name = "Arquivo"
        url = "/arquivo"